### ISSUE TITLE
Bug while trying to load BraketBackend

### ISSUE THREAD

**Issue by dhaycraft** [CQCL/pytket-braket#93]
Error while trying to create a braket backend due to issue with loading pytket module.:

Relevant python package versions:
pytket                          1.19.0
pytket-braket                   0.21.0

OS version
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

    from pytket.extensions.braket import BraketBackend
venv/lib/python3.10/site-packages/pytket/extensions/braket/__init__.py:21: in <module>
    from .backends import BraketBackend
venv/lib/python3.10/site-packages/pytket/extensions/braket/backends/__init__.py:18: in <module>
    from .braket import BraketBackend
venv/lib/python3.10/site-packages/pytket/extensions/braket/backends/braket.py:59: in <module>
    from pytket._tket.circuit._library import _TK1_to_RzRx  # type: ignore
E   ModuleNotFoundError: No module named 'pytket._tket.circuit._library'; 'pytket._tket.circuit' is not a package

This may also be an issue with other extensions.
https://github.com/CQCL/pytket-ionq/issues/27

I have tried these packet versions on Mac OS as well.

**Comment by cqc-alec** [comment]
Hi, can you please update to the latest version of pytket-braket (0.31.0) and try again? (Yes, we accidentally broke pytket backward compatibility for the extensions at one point but this should be fixed with the latest version.)

**Comment by cqc-melf** [comment]
Is this is not resolved, please reopen.
